In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 1000)

In [4]:
pythList=list(range(10000))

In [5]:
%time for _ in range(10): [item*3 for item in pythList]

CPU times: total: 0 ns
Wall time: 2.31 ms


In [6]:
%time for _ in range(1000000): arr1 = arr*3

CPU times: total: 1.33 s
Wall time: 1.33 s


In [7]:
array1=np.array([[1,2,3,4,5],[2,3.7,4,5,6]], dtype='int32')
print(array1)
array1.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [8]:
array1.dtype

dtype('int32')

In [9]:
np.zeros(2).dtype

dtype('float64')

In [10]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.ones((4, 6)).dtype

dtype('float64')

In [12]:
array1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

array1*array1*array1

In [13]:
array1+array1

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12]])

In [14]:
array1/array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.array([12, 12])

array([12, 12])

# Slicing

In [16]:
array1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [17]:
array2 = np.array([0,1,2,3,4,5])

In [18]:
arr = array2[4:6].copy()

In [19]:
arr

array([4, 5])

In [20]:
arr[0]=10

In [21]:
array2

array([0, 1, 2, 3, 4, 5])

In [22]:
arr

array([10,  5])

In [23]:
ar = np.array([[1,2,3],
               [4,5,6]])
arr3 = ar.sum(axis=0)
print(arr3)
arr4 = ar.sum(axis=1)
print(arr4)

[5 7 9]
[ 6 15]


In [24]:
b= np.array([[2,3,4],
            [7,8,6]])
c= np.array([[6,5,4],
            [2,0,3]])

In [25]:
arr5 = b.dot(c.transpose())
print(arr5)

[[ 43  16]
 [106  32]]


In [26]:
arr6 = np.cross(b,c)
print(arr6)

[[ -8  16  -8]
 [ 24  -9 -16]]


In [27]:
np.sort(b)

array([[2, 3, 4],
       [6, 7, 8]])

In [28]:
np.sort(b, axis=0)

array([[2, 3, 4],
       [7, 8, 6]])

In [29]:
%time
np.sort(b, axis=1, kind='mergesort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[2, 3, 4],
       [6, 7, 8]])

In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9,0,4,6,576,87,4,32,2,54])
brr = arr.reshape(9,2)
print(brr)

[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9   0]
 [  4   6]
 [576  87]
 [  4  32]
 [  2  54]]


In [54]:
np.argsort(arr)

array([ 9,  0,  1, 16,  2,  3, 10, 14,  4,  5, 11,  6,  7,  8, 15, 17, 13,
       12], dtype=int64)

In [55]:
np.argmin(brr)

9

In [56]:
np.argmax(arr)

12